# Configuration for LoginMSG.
# Use %player% for the player name in messages
# Use &[0-F] for colors in messages.

# Login message:
login-message: '&e&l%player%&e joined the game.'

# Logout message:
logout-message: '&e&l%player%&e left the game.'

# Custom messages.
# If two or more permissions match, the highest one will be used.
# Use the format:
# my permission:
#  login-message: 'some %player% logged in'
#  logout-message: 'some %player% logged out'
# (where a space in the permission is equal to a ".")
# If the permission specified is "server op", the message will display when an operator logs in.
# If the permission specified is "player [playername]", the message will display when [playername] logs in.
# If the permission specified is "not xxx", the message will display when the 'xxx' condition is not met (see above)
custom-messages:
  special message login:
    login-message: '&eTHE AMAZING &l%player%&e LOGGED IN! ROUND OF APPLAUSE'
    logout-message: '&eAaw... &l%player%&e logged out. You missed your chance to meet them!'
  server op:
    login-message: '&eThe moderator, &l%player%&e logged in.'
    logout-message: '&eThe moderator, &l%player%&e logged out.'
  player zoweb:
    login-message: '&eLoginMSG creator, zoweb, logged in!'
    logout-message: '&eGoodbye, zoweb!'
  not good person:
    login-message: '&e%player% is not a good person. And they dont have the good person permission.'
    logout-message: '&ePhew! %player% logged out!'


# Sounds on joining and leaving
# For a full list, check https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
use-sounds:
  join: true
  leave: true

# Login sound
login-sound: BLOCK_GLASS_BREAK

# Logout sound
logout-sound: BLOCK_FIRE_EXTINGUISH

# Custom sounds
# See the above 'custom messages' for info on how to use this
custom-sounds:
  special sound login:
    login-sound: ENTITY_CAT_PURREOW
    logout-sound: ENTITY_CAT_HISS
  server op:
    login-sound: ENTITY_GENERIC_EAT
    logout-sound: ENTITY_GENERIC_HURT
  player zoweb:
    login-sound: ENTITY_FIREWORK_SHOOT
    logout-sound: ENTITY_GHAST_DEATH
  not good person:
    login-sound: ENTITY_IRONGOLEM_DEATH
    logout-sound: ENTITY_PLAYER_SPLASH


# Enable MCStats? Pretty please :)
mc-stats: true