# Configuration for LoginMSG.
# Use %player% for the player name
# Use &[0-F] for colors.

# If updating, change leave-message to logout-message.

# Login message:
login-message: '&e&l%player%&e joined the game.'

# Logout message:
logout-message: '&e&l%player%&e left the game.'